CREATE TABLE ITEM (ID INT PRIMARY KEY, NAME VARCHAR(255) UNIQUE, UNIT_PRICE DECIMAL(20, 2));
INSERT INTO ITEM VALUES(1, 'Jacket', '49.9');
INSERT INTO ITEM VALUES(2, 'Trouser', '35.50');
INSERT INTO ITEM VALUES(3, 'Shirt', '12.50');
INSERT INTO ITEM VALUES(4, 'Tie', '9.50');
